services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Warehouse
    ports:
      - "5007:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
