name: warehouses-delison

services:
  api:
    image: warehouses-delison-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Warehouse-delison
    ports:
      - "6007:80"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
    restart: unless-stopped
